version: "3"
services:
  node:
    build: ./docker/node
    tty: true
    volumes:
      - ./app:/app
    working_dir: /app
    # command: [sh ./build_and_run.sh]

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_DATABASE=typescript
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
      - 13306:3306

volumes:
  db-store:
